

#ifndef WTFILEUTILS_COREEVENTS_H
#define WTFILEUTILS_COREEVENTS_H

namespace ecs {
  ECS_UNICAST_EVENT_TYPE(EventEntityCreated)
  ECS_UNICAST_EVENT_TYPE(EventEntityDestroyed)
  ECS_BROADCAST_EVENT_TYPE(EventEntitySomething)
}


#endif //WTFILEUTILS_COREEVENTS_H
