

if (NOT FUNCTIONS_INCLUDED)
    set(FUNCTIONS_INCLUDED TRUE)
    function(print_stats)
        message(STATUS "C Compiler: ${CMAKE_C_COMPILER}")
        message(STATUS "C++ Compiler: ${CMAKE_CXX_COMPILER}")
        message(STATUS "C++ Compiler ID: ${CMAKE_CXX_COMPILER_ID}")
        message(STATUS "C Compiler ID: ${CMAKE_C_COMPILER_ID}")
        message(STATUS "C++ Compiler Version: ${CMAKE_CXX_COMPILER_VERSION}")
        message(STATUS "System Name: ${CMAKE_SYSTEM_NAME}")
        message(STATUS "System Processor: ${CMAKE_SYSTEM_PROCESSOR}")
        message(STATUS "Generator Platform: ${CMAKE_GENERATOR_PLATFORM}")
        message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")
    endfunction()

    function(set_compiler_flags)
        # set(BUILD_SHARED_LIBS OFF)
        # add_definitions(-D_GLIBCXX_USE_CXX11_ABI=1)

        # add_compile_definitions(_TARGET_SIMD_SSE=2)
        # add_compile_definitions(WITH_SHOW_INCLUDES=ON)

        # THIS IS BAD BUT I DUNNO HOW TO DO IT AND DIDNT LOOK IT UP
        if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
            if(CMAKE_BUILD_TYPE STREQUAL "Release")
                set(BUILD_SHARED_LIBS OFF)
                # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libgcc -static-libstdc++ -static" PARENT_SCOPE)
                # set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libgcc -static-libstdc++ -static" PARENT_SCOPE)
                if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zi" PARENT_SCOPE)
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /debug" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /O2 /wd4068" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT" PARENT_SCOPE)
                    # set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded" PARENT_SCOPE)
                elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wno-ignored-attributes -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    # set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wno-ignored-attributes -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                endif ()
            elseif (CMAKE_BUILD_TYPE STREQUAL "Debug")
                if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                    add_compile_options(/showIncludes)
                    # add_compile_options(/fsanitize=address)
                    # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /fsanitize=address " PARENT_SCOPE)
                    string(REPLACE "/RTC1" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}" PARENT_SCOPE)
                    # set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebug" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zi /showIncludes /Y- /MTd" PARENT_SCOPE)
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /debug" PARENT_SCOPE)
                elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -Wno-ignored-attributes -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    add_compile_options(-msse4.2)
                    # set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -msse4.2 -march=native" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse4.2 -march=native -O0 -Wno-ignored-attributes -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                endif ()
            else()
                if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                    add_compile_options(/showIncludes)
                    # add_compile_options(/fsanitize=address)
                    # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /fsanitize=address /MTd" PARENT_SCOPE)
                endif ()
            endif ()
        elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
            if(CMAKE_BUILD_TYPE STREQUAL "release")
                if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-ignored-attributes -O3 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-ignored-attributes -O3 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                endif ()
            elseif (CMAKE_BUILD_TYPE STREQUAL "Debug")
                if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpermissive -O0 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpermissive -Wno-ignored-attributes -Wall -Wextra -pedantic" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fPIC -fsanitize=address" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -fpermissive -Wno-ignored-attributes -O0 -Wno-multichar -Wno-unused-parameter -Wall -Wextra -pedantic -fsanitize=address -fno-omit-frame-pointer -g" PARENT_SCOPE)
                endif ()
            endif ()
        endif ()
    endfunction()


    function(set_data_folders_loc)
        message("set config files dir to ${CMAKE_CURRENT_SOURCE_DIR}/config_dir")
        add_compile_definitions(CONFIG_DIR="${CMAKE_CURRENT_SOURCE_DIR}/config_dir")

        message("set base dir to ${CMAKE_CURRENT_SOURCE_DIR}")
        add_compile_definitions(BASE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")


        message("set warthunder dir to D:/SteamLibrary/steamapps/common/War Thunder")
        add_compile_definitions(WARTHUNDER_DIR="D:/SteamLibrary/steamapps/common/War Thunder")
    endfunction()
endif ()
