// generated by replay parser codegen version 0.2
#pragma once

class BaseZone : public danet::ReplicatedObject {
public:
  DECL_REPLICATION(BaseZone, danet::ReplicatedObject)
  danet::ReflectionVar<uint8_t> armyNo{"armyNo", &flags, 2};
  danet::ReflectionVar<uint16_t> flags{"flags", nullptr, 3};
  BaseZone() : ReplicatedObject()  {
    varList.head = &armyNo;
    varList.tail = &flags;
  }
};

