// generated by replay parser codegen version 0.2
#pragma once

class BombingZone : public danet::ReplicatedObject {
public:
  DECL_REPLICATION(BombingZone, danet::ReplicatedObject)
  danet::ReflectionVar<uint8_t> armyNo{"armyNo", &flags, 2};
  danet::ReflectionVar<uint16_t> flags{"flags", &curZoneIntegrity, 3};
  danet::ReflectionVar<float> curZoneIntegrity{"curZoneIntegrity", nullptr, 67};
  BombingZone() : ReplicatedObject()  {
    varList.head = &armyNo;
    varList.tail = &curZoneIntegrity;
  }
};

