// generated by replay parser codegen version 0.2
#pragma once

class BombingZone : public MissionZone {
public:
  DECL_REPLICATION(BombingZone, MissionZone)
  danet::ReflectionVar<float> curZoneIntegrity{"curZoneIntegrity", nullptr, 67};
  BombingZone() : MissionZone()  {
    flags.next = &curZoneIntegrity;
    varList.tail = &curZoneIntegrity;
  }
};

