// generated by replay parser codegen version 0.2
#pragma once

class MissionArea : public danet::ReplicatedObject {
public:
  DECL_REPLICATION(MissionArea, danet::ReplicatedObject)
  TMatrix tm{};
  danet::ReflectionVar<danet::AreaFlagsEnum> areaFlags{"areaFlags", nullptr, 2};
  MissionArea() : ReplicatedObject()  {
    varList.head = &areaFlags;
    varList.tail = &areaFlags;
  }
};

