// generated by replay parser codegen version 0.2
#pragma once

class MissionZone : public danet::ReplicatedObject {
public:
  DECL_REPLICATION(MissionZone, danet::ReplicatedObject)
  MissionArea* area{};
  danet::ReflectionVar<uint8_t> armyNo{"armyNo", &flags, 2};
  danet::ReflectionVar<uint16_t> flags{"flags", nullptr, 3};
  MissionZone() : ReplicatedObject()  {
    varList.head = &armyNo;
    varList.tail = &flags;
  }
};

