// generated by replay parser codegen version 0.2
#pragma once

class PickupZone : public MissionZone {
public:
  DECL_REPLICATION(PickupZone, MissionZone)
  danet::ReflectionVar<bool> showOnTacticalMap{"showOnTacticalMap", nullptr, 67};
  PickupZone() : MissionZone()  {
    flags.next = &showOnTacticalMap;
    varList.tail = &showOnTacticalMap;
  }
};

