// generated by replay parser codegen version 0.2

#pragma once
#include "Module.h"

class PyCodegenObjects : protected Module {
public:
  PyCodegenObjects() : Module() {}
  void include(py::module_ &m);
};

extern PyCodegenObjects py_codegen_objects;
