// generated by replay parser codegen version 0.2

#pragma once
#include "Module.h"

class PyCodegenTypes : protected Module {
public:
  PyCodegenTypes() : Module() {}
  void include(py::module_ &m);
};

extern PyCodegenTypes py_codegen_types;
