// generated by replay parser codegen version 0.2
#include "modules/mpi/codegen_objects.h"
#include "modules/mpi/types.h"
#include "mpi/codegen/ReflIncludes.h"
#include "modules/mpi/mpi.h"
PyCodegenObjects py_codegen_objects;
void PyCodegenObjects::include(py::module_ &m) {
  DO_INCLUDE()
  py_mpi_types.include(m);
  py_mpi.include(m);
  auto mpi = m.def_submodule("mpi");
  py::class_<MPlayer, danet::ReflectableObject, std::unique_ptr<MPlayer, py::nodelete>>(mpi, "MPlayer")
    .def_readonly("currentOwnedUnits", &MPlayer::currentOwnedUnits)
    .def_readonly("allOwnedUnits", &MPlayer::allOwnedUnits)
    .def_readonly("uid", &MPlayer::uid)
    .def_readonly("invitedNickName", &MPlayer::invitedNickName)
    .def_readonly("nickLocKey", &MPlayer::nickLocKey)
    .def_readonly("ClanTag", &MPlayer::ClanTag)
    .def_readonly("Title", &MPlayer::Title)
    .def_readonly("publicFlags", &MPlayer::publicFlags)
    .def_readonly("decals", &MPlayer::decals)
    .def_readonly("team", &MPlayer::team)
    .def_readonly("countryId", &MPlayer::countryId)
    .def_readonly("memberId", &MPlayer::memberId)
    .def_readonly("customState", &MPlayer::customState)
    .def_readonly("score", &MPlayer::score)
    .def_readonly("dummyForSupportPlanes", &MPlayer::dummyForSupportPlanes)
    .def_readonly("dummyForCrewUnitsList", &MPlayer::dummyForCrewUnitsList)
    .def_readonly("disabledByMatchingSlots", &MPlayer::disabledByMatchingSlots)
    .def_readonly("brokenSlots", &MPlayer::brokenSlots)
    .def_readonly("wasReadySlots", &MPlayer::wasReadySlots)
    .def_readonly("spareAircraftInSlots", &MPlayer::spareAircraftInSlots)
    .def_readonly("ownedSlots", &MPlayer::ownedSlots)
    .def_readonly("classinessMark", &MPlayer::classinessMark)
    .def_readonly("timeToRespawn", &MPlayer::timeToRespawn)
    .def_readonly("timeToRespawnInCoop", &MPlayer::timeToRespawnInCoop)
    .def_readonly("forcedRespawn", &MPlayer::forcedRespawn)
    .def_readonly("timeToKick", &MPlayer::timeToKick)
    .def_readonly("guiState", &MPlayer::guiState)
    .def_readonly("spectatedModelIndex", &MPlayer::spectatedModelIndex)
    .def_readonly("dummyForCountUsedSlots", &MPlayer::dummyForCountUsedSlots)
    .def_readonly("dummyForSpawnCosts", &MPlayer::dummyForSpawnCosts)
    .def_readonly("dummyForSpawnDelayTimes", &MPlayer::dummyForSpawnDelayTimes)
    .def_readonly("dummyForKillStreaksProgress", &MPlayer::dummyForKillStreaksProgress)
    .def_readonly("state", &MPlayer::state)
    .def_readonly("squadScore", &MPlayer::squadScore)
    .def_readonly("ownedUnitRef", &MPlayer::ownedUnitRef)
    .def_readonly("controlledUnitRef", &MPlayer::controlledUnitRef)
    .def_readonly("supportUnitRef", &MPlayer::supportUnitRef)
    .def_readonly("wreckedPartShipUnitRef", &MPlayer::wreckedPartShipUnitRef)
    .def_readonly("dummyForRoundScore", &MPlayer::dummyForRoundScore)
    .def_readonly("dummyForPlayerStat", &MPlayer::dummyForPlayerStat)
    .def_readonly("dummyForFootballStat", &MPlayer::dummyForFootballStat)
    .def_readonly("realNick", &MPlayer::realNick)
    .def_readonly("squadronId", &MPlayer::squadronId)
    .def_readonly("forceLockTarget", &MPlayer::forceLockTarget)
    .def_readonly("cachedIsAutoSquad", &MPlayer::cachedIsAutoSquad)
    .def_readonly("nickFrame", &MPlayer::nickFrame)
    .def_readonly("missionSupportUnitRef", &MPlayer::missionSupportUnitRef)
    .def_readonly("missionSupportUnitEnabled", &MPlayer::missionSupportUnitEnabled)
    .def_readonly("rageTokens", &MPlayer::rageTokens)
  ;
  py::class_<TeamData, danet::ReflectableObject, std::unique_ptr<TeamData, py::nodelete>>(mpi, "TeamData")
    .def_readonly("score", &TeamData::score)
    .def_readonly("tickets", &TeamData::tickets)
    .def_readonly("orderCooldownTotal", &TeamData::orderCooldownTotal)
    .def_readonly("orderCooldownLeft", &TeamData::orderCooldownLeft)
    .def_readonly("spawnScore", &TeamData::spawnScore)
    .def_readonly("roundScore", &TeamData::roundScore)
  ;
  py::class_<GlobalElo, danet::ReflectableObject, std::unique_ptr<GlobalElo, py::nodelete>>(mpi, "GlobalElo")
    .def_readonly("teamAvgEloRatings", &GlobalElo::teamAvgEloRatings)
  ;
  py::class_<GeneralState, danet::ReflectableObject, std::unique_ptr<GeneralState, py::nodelete>>(mpi, "GeneralState")
    .def_readonly("lastSuperArtilleryTime", &GeneralState::lastSuperArtilleryTime)
    .def_readonly("dummyForExitZonesSettings", &GeneralState::dummyForExitZonesSettings)
    .def_readonly("battleAreaChangeTime", &GeneralState::battleAreaChangeTime)
    .def_readonly("battleAreaChangeToId", &GeneralState::battleAreaChangeToId)
    .def_readonly("forcedMapCellsAir", &GeneralState::forcedMapCellsAir)
    .def_readonly("forcedMapCellsGround", &GeneralState::forcedMapCellsGround)
    .def_readonly("useCustomSuperArtillery", &GeneralState::useCustomSuperArtillery)
    .def_readonly("waterWindStrengthClamp", &GeneralState::waterWindStrengthClamp)
    .def_readonly("weatherEffectsDummyVar", &GeneralState::weatherEffectsDummyVar)
    .def_readonly("timeLeft", &GeneralState::timeLeft)
    .def_readonly("dummyForBombingEvent", &GeneralState::dummyForBombingEvent)
    .def_readonly("dummyForUnlimitedControlEvent", &GeneralState::dummyForUnlimitedControlEvent)
    .def_readonly("customState", &GeneralState::customState)
  ;
  py::class_<MissionArea, danet::ReplicatedObject, std::unique_ptr<MissionArea, py::nodelete>>(mpi, "MissionArea")
    .def_readonly("tm", &MissionArea::tm)
    .def_readonly("areaFlags", &MissionArea::areaFlags)
  ;
  py::class_<MissionZone, danet::ReplicatedObject, std::unique_ptr<MissionZone, py::nodelete>>(mpi, "MissionZone")
    .def_readonly("area", &MissionZone::area)
    .def_readonly("armyNo", &MissionZone::armyNo)
    .def_readonly("flags", &MissionZone::flags)
  ;
  py::class_<BombingZone, MissionZone, std::unique_ptr<BombingZone, py::nodelete>>(mpi, "BombingZone")
    .def_readonly("curZoneIntegrity", &BombingZone::curZoneIntegrity)
  ;
  py::class_<CaptureZone, MissionZone, std::unique_ptr<CaptureZone, py::nodelete>>(mpi, "CaptureZone")
    .def_readonly("mpTimeX100", &CaptureZone::mpTimeX100)
    .def_readonly("conqTeam", &CaptureZone::conqTeam)
    .def_readonly("iconIdx", &CaptureZone::iconIdx)
    .def_readonly("dummyVarForCapturers", &CaptureZone::dummyVarForCapturers)
    .def_readonly("dummyVarForCapturePart", &CaptureZone::dummyVarForCapturePart)
    .def_readonly("dummyVarForNumOfActiveCapturers", &CaptureZone::dummyVarForNumOfActiveCapturers)
  ;
  py::class_<RearmZone, MissionZone, std::unique_ptr<RearmZone, py::nodelete>>(mpi, "RearmZone")
  ;
  py::class_<ExitZone, MissionZone, std::unique_ptr<ExitZone, py::nodelete>>(mpi, "ExitZone")
  ;
  py::class_<PickupZone, MissionZone, std::unique_ptr<PickupZone, py::nodelete>>(mpi, "PickupZone")
    .def_readonly("showOnTacticalMap", &PickupZone::showOnTacticalMap)
  ;
  py::class_<UnitWeaponsMask, danet::ReflectableObject, std::unique_ptr<UnitWeaponsMask, py::nodelete> >(
              mpi, "UnitWeaponsMask")
          .def_readonly("dummyVarForAmmoPartsMask", &UnitWeaponsMask::dummyVarForAmmoPartsMask);
}