// generated by replay parser codegen version 0.2
#include "modules/mpi/mpi.h"
#include "modules/mpi/codegen_types.h"
#include "mpi/types.h"
#include "modules/mpi/bind_array.h"
#include "pybind11/stl_bind.h"
PyCodegenTypes py_codegen_types{};
void PyCodegenTypes::include(py::module_ &m) {
  DO_INCLUDE()
  py_mpi.include(m);
  auto mpi = m.def_submodule("mpi");
  py::class_<danet::RoundScore>(mpi, "RoundScore")
    .def_readonly("combined", &danet::RoundScore::combined)
    .def_readonly("scores", &danet::RoundScore::scores)
    ;
  py::class_<danet::dummyForFootballStat>(mpi, "dummyForFootballStat")
    .def_readonly("v1", &danet::dummyForFootballStat::v1)
    .def_readonly("v2", &danet::dummyForFootballStat::v2)
    .def_readonly("v3", &danet::dummyForFootballStat::v3)
    ;
  py::class_<danet::Crew>(mpi, "Crew")
    .def_readonly("e1", &danet::Crew::e1)
    .def_readonly("e2", &danet::Crew::e2)
    .def_readonly("v1", &danet::Crew::v1)
    .def_readonly("v2", &danet::Crew::v2)
    ;
  py::class_<danet::CrewUnitsList>(mpi, "CrewUnitsList")
    .def_readonly("crew", &danet::CrewUnitsList::crew)
    ;
  py::class_<danet::dummyForPlayerStat>(mpi, "dummyForPlayerStat")
    .def_readonly("v1", &danet::dummyForPlayerStat::v1)
    .def_readonly("v2", &danet::dummyForPlayerStat::v2)
    .def_readonly("v3", &danet::dummyForPlayerStat::v3)
    .def_readonly("v4", &danet::dummyForPlayerStat::v4)
    .def_readonly("v5", &danet::dummyForPlayerStat::v5)
    .def_readonly("v6", &danet::dummyForPlayerStat::v6)
    .def_readonly("v7", &danet::dummyForPlayerStat::v7)
    .def_readonly("v8", &danet::dummyForPlayerStat::v8)
    .def_readonly("v9", &danet::dummyForPlayerStat::v9)
    .def_readonly("v10", &danet::dummyForPlayerStat::v10)
    .def_readonly("v11", &danet::dummyForPlayerStat::v11)
    .def_readonly("v12", &danet::dummyForPlayerStat::v12)
    .def_readonly("v13", &danet::dummyForPlayerStat::v13)
    .def_readonly("v14", &danet::dummyForPlayerStat::v14)
    .def_readonly("v15", &danet::dummyForPlayerStat::v15)
    .def_readonly("v16", &danet::dummyForPlayerStat::v16)
    .def_readonly("v17", &danet::dummyForPlayerStat::v17)
    .def_readonly("v18", &danet::dummyForPlayerStat::v18)
    .def_readonly("v19", &danet::dummyForPlayerStat::v19)
    .def_readonly("v20", &danet::dummyForPlayerStat::v20)
    .def_readonly("v21", &danet::dummyForPlayerStat::v21)
    .def_readonly("v22", &danet::dummyForPlayerStat::v22)
    .def_readonly("v23", &danet::dummyForPlayerStat::v23)
    .def_readonly("v24", &danet::dummyForPlayerStat::v24)
    ;
  py::class_<danet::streak>(mpi, "streak")
    .def_readonly("v1", &danet::streak::v1)
    .def_readonly("v2", &danet::streak::v2)
    .def_readonly("v3", &danet::streak::v3)
    ;
  py::class_<danet::dummyForKillStreaksProgress>(mpi, "dummyForKillStreaksProgress")
    .def_readonly("vals", &danet::dummyForKillStreaksProgress::vals)
    ;
  py::class_<danet::teamAvgEloRatings>(mpi, "teamAvgEloRatings")
    .def_readonly("team1", &danet::teamAvgEloRatings::team1)
    .def_readonly("team2", &danet::teamAvgEloRatings::team2)
    .def_readonly("team3", &danet::teamAvgEloRatings::team3)
    ;
  py::class_<danet::zigZagPair>(mpi, "zigZagPair")
    .def_readonly("v1", &danet::zigZagPair::v1)
    .def_readonly("v2", &danet::zigZagPair::v2)
    ;
  py::class_<danet::dummyForExitZonesSettings>(mpi, "dummyForExitZonesSettings")
    .def_readonly("vals", &danet::dummyForExitZonesSettings::vals)
    ;
  py::class_<danet::WeatherEffect>(mpi, "WeatherEffect")
    .def_readonly("name", &danet::WeatherEffect::name)
    .def_readonly("effect_data", &danet::WeatherEffect::effect_data)
    ;
  py::class_<danet::WeatherEffects>(mpi, "WeatherEffects")
    .def_readonly("effects", &danet::WeatherEffects::effects)
    ;
  py::class_<danet::UnitIdStruct>(mpi, "UnitIdStruct")
    .def_readonly("uid", &danet::UnitIdStruct::uid)
    .def_readonly("thang", &danet::UnitIdStruct::thang)
    ;
  py::bind_vector<std::vector<uint32_t>>(mpi, "Vector_uint32_t");

  py::bind_vector<std::vector<danet::Crew>>(mpi, "Vector_Crew");

  py::bind_vector<std::vector<danet::streak>>(mpi, "Vector_streak");

  py::bind_vector<std::vector<danet::zigZagPair>>(mpi, "Vector_zigZagPair");

  py::bind_vector<std::vector<danet::WeatherEffect>>(mpi, "Vector_WeatherEffect");

}